spring.application.name=course-service
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/course_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8081

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8762/eureka}
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
jwt.secret=change_this_to_a_long_random_string_at_least_32_chars
jwt.expiration=3600000


management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true