# build stage
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -B package -DskipTests

# runtime stage
FROM eclipse-temurin:17-jre-jammy
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=build /app/target/service-registry-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8762

ENTRYPOINT ["java", "-jar", "/app/app.jar"]